// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs15xzPi76ZJtokfv60pbb5d3CAopVHAw',
    appId: '1:254176556033:web:3f03e50f74568d46763c00',
    messagingSenderId: '254176556033',
    projectId: 'chat-app-e8711',
    authDomain: 'chat-app-e8711.firebaseapp.com',
    storageBucket: 'chat-app-e8711.appspot.com',
    measurementId: 'G-H8SCDSPJXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uWrv_q8MCfDdlpUx7qovLIRHROUenVE',
    appId: '1:254176556033:android:5fcbe513cfab55ac763c00',
    messagingSenderId: '254176556033',
    projectId: 'chat-app-e8711',
    storageBucket: 'chat-app-e8711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASq53sIM6fIpyLXCgC4ZQLss6IzwMhi3M',
    appId: '1:254176556033:ios:85b82dbf5a254630763c00',
    messagingSenderId: '254176556033',
    projectId: 'chat-app-e8711',
    storageBucket: 'chat-app-e8711.appspot.com',
    iosClientId: '254176556033-v10kh7r70dm7dgi5s8udq7l1moruc2qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
